spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jps:
    generate-dbl: false
    hibernate:
      ddl-auto: none
    show-sql: true