package com.example.bootcamp.domain.volunteer;

import lombok.Data;

@Data
public class Volunteer {
    /*
        CREATE TABLE "volunteer" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(100) NOT NULL,
            "surname" VARCHAR(100) NOT NULL,
            "patronymic" VARCHAR(100),
            "about_me" VARCHAR(300),
            "telephone" VARCHAR(20) NOT NULL UNIQUE,
            "email" VARCHAR(255) NOT NULL UNIQUE,
            "password" VARCHAR(255) NOT NULL,
            "birthday" DATE NOT NULL,
            "city" VARCHAR(50) NOT NULL,
            "telegram_link" VARCHAR(255),
            "vk_link" VARCHAR(255),
            "admin" INTEGER NOT NULL,
            "center_id" INTEGER,
            "creater_at" TIMESTAMP NOT NULL,
            "profile_image_url" VARCHAR(100),
            "medical_book" BOOLEAN,
            "driver_license" BOOLEAN,
            PRIMARY KEY("id")
        );
     */
}
